name: Run Postman Collection

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ejecutar-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install Newman
        run: npm install -g newman

      - name: Install Newman Reporter
        run: npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection
        if: always()
        run: |
          newman run "tests/DummyJSON_API_Test.postman_collection.json" \
            -r htmlextra \
            --reporter-htmlextra-export tests/report.html \
            --suppress-exit-code

      - name: Check if report was generated
        if: always()
        run: |
          if [ -f tests/report.html ]; then
            echo "✅ Report generated successfully."
          else
            echo "❌ Report not found. Skipping email step."
            exit 0
          fi
      - name: Upload report as artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: postman-report
          path: tests/report.html

      - name: Send email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USUARIO }}
          password: ${{ secrets.EMAIL_CONTRASENA }}
          subject: "Postman Run Results"
          to: maxscripts23@gmail.com
          from: "Postman CI <maxscripts23@gmail.com>"
          body: |
            Hello Max 👋

            The automated run of your Postman collection has completed.
            Please find the attached report with the test results.

            Have a great day! 🚀
          attachments: tests/report.html